import 'react-toastify/dist/ReactToastify.css'
import { Montserrat } from 'next/font/google'
import './globals.css'
import Head from 'next/head'
import { ToastContainer } from 'react-toastify'

const montserrat = Montserrat({
    subsets: ['latin']
})

export const metadata = {
    title: 'IOT Web Application',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <>
                <Head>
                    <title>{metadata.title}</title>
                    <meta name="description" content={metadata.description} />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <body className={montserrat.className}>
                    <ToastContainer />
                    {children}
                </body>
            </>
        </html>
    )
}
